#!/usr/bin/env bash
#
# Build the local-first dashcam viewer and sync its production bundle into the
# Tesla Tracker Home Assistant integration so it can be served as a sidebar
# panel.
#
# Home Assistant / HACS cannot run `npm`, so the built panel is committed into
# `custom_components/tesla_tracker/panel/`. Run this script whenever the viewer
# changes (CI also runs it before cutting a release so the committed bundle can
# never go stale).
#
# Usage:  bash scripts/build_panel.sh
#
set -euo pipefail

# Resolve repo root from this script's location (works regardless of CWD).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

VIEWER_DIR="${REPO_ROOT}/apps/dashcam-viewer"
DIST_DIR="${VIEWER_DIR}/dist"
PANEL_DIR="${REPO_ROOT}/custom_components/tesla_tracker/panel"

echo "==> Building dashcam viewer (${VIEWER_DIR})"
cd "${VIEWER_DIR}"

if [ ! -d node_modules ]; then
  echo "==> Installing viewer dependencies (npm ci)"
  npm ci
fi

# Vite is configured with base: './' so all asset URLs in the built index.html
# are relative; the bundle therefore works from HA's arbitrary static mount.
npm run build

echo "==> Syncing dist -> ${PANEL_DIR}"
rm -rf "${PANEL_DIR}"
mkdir -p "${PANEL_DIR}"
cp -R "${DIST_DIR}/." "${PANEL_DIR}/"

# Marker so it's obvious the directory is generated, never hand-edited.
cat > "${PANEL_DIR}/.gitattributes" <<'EOF'
# Generated by scripts/build_panel.sh from apps/dashcam-viewer. Do not edit by hand.
* linguist-generated=true
EOF

echo "==> Panel contents:"
( cd "${PANEL_DIR}" && find . -type f | sort )

echo "==> Done. Commit custom_components/tesla_tracker/panel/ so HACS ships a working panel."
